sudo: false

language: node_js

node_js:
  - 4.5.0

git:
  depth: 3

addons:
  apt:
    packages:
      - libfontconfig

before_script:
  - echo "module.exports = { browser:'phantomjs', webdriverio:{ baseUrl:'https://dr-dev.envage.co.uk' } }" > chimp.js
